### PR TITLE
Events - do not use `dbName` & fix `futureDate` and `pastDate`

### LINKED ISSUE #714: Error setting filters in event list block
**Describe the bug**
We get a "cannot read properties of undefined (reading 'tenant')" error when changing the event types filter on an event list block on home page - needs further investigation. Happening on events preview environment.

**To Reproduce**

1. Visit a homePages document on the `events` branch
2. Change the event types filter on the event list block that was created from the seed script on every home page
3. See the "cannot read properties of undefined (reading 'tenant')" error appear in a toast
4. Try to save the document and observe the FOREIGN KEY constraint error

**Expected behavior**
No errors for this flow

**Screenshots**
https://www.loom.com/share/56e917402ed94a50a5bf37c36cd4c790

**Environment details**

- Desktop
- Chrome

### PR DESCRIPTION
**Pull request by rchlfryn**
## Description
Shortens database names to avoid using `dbName` which was causing a foreign key error
https://github.com/payloadcms/payload/issues/14350

Fixes `futureDate` and `pastDate` seed functions

## Related Issues
Fixes #714 

## Key Changes
- Shorten db names
- `futureDate` and `pastDate` functions were erroring out because the month offset was trying to set months to 13 & 14 which don't exist. I fixed this by adding a mod function and year to wrap the dates. 

## Migration Explanation
Need migration to update names

### CODE REVIEW

File: src/fields/EventQuery/config.ts [hunk 1]
```diff
@@ -39,16 +39,16 @@ export const defaultStylingFields = (additionalFilters?: Field[]): Field[] => [
...
     required: true,
     options: [
       {
-        label: 'Do it for me',
+        label: 'Use filters',
         value: 'dynamic',
       },
       {
-        label: 'Let me choose',
+        label: 'Manually',
```
Comment (busbyk) [inline src/fields/EventQuery/config.ts:51]: 👏

**Review by busbyk — APPROVED** [review]
Looks good!
