### PR TITLE
Remove permissive read

### LINKED ISSUE #294: baseListFilter not working as expected for teams and bios
This is potentially an issue with our permissive read access control functions. 

When viewing Teams and Biographies users can see all tenants when they should only see tenants they have tenant-scoped roles for. 

Needs further investigation.

### PR DESCRIPTION
**Pull request by busbyk**
Resolves #294 

Removing permissive reads means that we don't need to change the filterByTenant baseListFilter since we're now letting roles dictate read access control which kicks in when there isn't a tenant cookie set to filter list results. 

I also: 
- added access control via byTenantRole to the redirects and form builder plugins
- removed the unused payload cloud plugin that we don't intend to use

### CODE REVIEW

File: src/access/filterByTenant.ts [hunk 1]
```diff
@@ -1,10 +1,20 @@
...
+
+  if (selectedTenant) {
+    return {
+      tenants: {
+        equals: selectedTenant,
+      },
+    }
+  }
+
+  return null
```
Comment (busbyk) [inline src/access/filterByTenant.ts:19]: This is from https://github.com/payloadcms/payload/blob/main/packages/plugin-multi-tenant/src/list-filters/filterDocumentsBySelectedTenant.ts

**Review by yuliadub — APPROVED** [review]
this makes sense to me!
