### PR TITLE
Fix relations fields to be tenant exclusive on posts

### LINKED ISSUE #305: Change default column for Role Assignments
Under roles assignments - change column to show name instead of id

add to `admin` `useAsTitle: 'name',`

### PR DESCRIPTION
**Pull request by rchlfryn**
#### Description
This PR solves three issues I noticed when working on blogs.
* The first issue I noticed was as a super admin, when navigating to a post, if you try to select an author or related post, it would show all options from all tenants. This was especially confusing because we have the same title for post across multiple tenants. I think the simple fix was to add a filter on the fields.
* The second issue I noticed was the authors selected in the seed script for Sierra and sawtooth of were NWAC biographies. This is a bit more involved in touches the `populateAuthor` hook, which I am not familiar with, but it does properly select an author within the avalanche center.
* Finally this resolves #305

### CODE REVIEW

File: src/collections/Posts/hooks/populateAuthors.ts
Comment (rchlfryn) [inline src/collections/Posts/hooks/populateAuthors.ts:1]: This change doesn't seem correct based on the comments, but I tested it and it work. I am not really sure what this was doing so someone feel free to explain.

Comment (stevekuznetsov) [reply src/collections/Posts/hooks/populateAuthors.ts:1]: I think it just depends on what we want the outcome to be here - if we want authors on a post to be `User`, and we want it to display nicely, we need to have `User` records with avatars, etc. We know we can't associate every `Biography` with a `User` (not only do we have separate bios for the same user across multiple centers, but we also have emeritus/post-humous bios). We might also ask that every `User` have a `Biography` in the tenants they are writing for, which would let you search this.

File: src/collections/Posts/index.ts [hunk 1]
```diff
@@ -130,6 +130,13 @@ export const Posts: CollectionConfig<'posts'> = {
       hasMany: true,
       relationTo: 'biographies',
       required: true,
+      filterOptions: ({ data }) => {
```
Comment (busbyk) [inline src/collections/Posts/index.ts:133]: It's weird that the baseListFilter on biographies doesn't apply here by default. But good to know!

File: src/collections/Posts/hooks/populateAuthors.ts
Comment (busbyk) [reply src/collections/Posts/hooks/populateAuthors.ts:1]: Wait, I don't think we're even using populatedAuthors anywhere. It's only used by the https://github.com/NWACus/web/blob/main/src/utilities/formatAuthors.ts utility but that's not used anywhere. 

The Posts collection is already using the biographies collection for author relationships. 

We should remove populateAuthors and formatAuthors.

**Review by busbyk — CHANGES_REQUESTED** [review]
> Finally this resolves #305 

Did you mention the correct issue here? This PR doesn't change anything related to the role assignments collection.

**Comment by rchlfryn** [comment]
@busbyk `populateAuthors` is being run `afterRead` on posts
https://github.com/NWACus/web/blob/main/src/collections/Posts/index.ts#L214

I am fine removing it, I just want to know if we should or not. I will bring this up at stand today

**Comment by busbyk** [comment]
> @busbyk `populateAuthors` is being run `afterRead` on posts https://github.com/NWACus/web/blob/main/src/collections/Posts/index.ts#L214
> 
> I am fine removing it, I just want to know if we should or not. I will bring this up at stand today

Yea that's there to allow for displaying user fields on the frontend since read access for the users collection is restricted. 

But we don't need that for two reasons:
1. We don't respect access control in our server components. We use the local API which overrides access by default. 
2. We're not using the users collection as authors anymore, we're using the biographies collection. #321 will make it so that biographies no longer has permissive read but since our server components use the local API and we don't use the REST API at all right now, this isn't an issue. populatedAuthors isn't used in the admin panel anywhere. 

Although I suppose there may be a little more to this if we want to use the user related to a biography for the name instead of the biography name https://github.com/NWACus/web/issues/309.

So worth considering that.

**Review by busbyk — APPROVED** [review]
🤘

**Comment by rchlfryn** [comment]
I will merge this and we can remove `populateAuthors` as needed in #321
