### PR TITLE
Bug - fix events table long name, sortable header, and loading

### LINKED ISSUE #748: Long Class Title Overflows Table Column
Image

Seen on https://snfac.avy-fx.org/

### PR DESCRIPTION
**Pull request by rchlfryn**
## Description
There were a few issues with event tables noticed on Sawtooths homepage post launch.

## Related Issues
Fixes #748 

## Key Changes
- Renders `SortableHeader` outside of function to prevent constant re-rendering
- Wrap long event name titles
- Use container queries to avoid scrolling window when EventTable is used in content columns

## Screenshots / Demo
Weather-Tools-Sawtooth-Avalanche-Center-12-03-2025_06_18_PM

### CODE REVIEW

File: src/components/EventsTable/index.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ import {
 } from '@/components/ui/table'
 import type { Event } from '@/payload-types'
 import { formatDateTime } from '@/utilities/formatDateTime'
+import { Link } from '@payloadcms/ui'
```
Comment (busbyk) [inline src/components/EventsTable/index.tsx]: I think this should be imported from `next/link`?

**Review by busbyk — COMMENTED** [review]
I think it would be nice to match more of the EventList styling like background color, spacing between heading and content, border, and rounded corners:

Image

At least the background color and spacing between heading and content.

File: src/components/EventsTable/index.tsx (hunk 1 above)
Comment (rchlfryn) [reply src/components/EventsTable/index.tsx]: Updated in [986f3a6](https://github.com/NWACus/web/pull/756/commits/986f3a6aaffc95bd723a68566c60efea491932de)

**Comment by rchlfryn** [comment]
@busbyk I updated the styling as requested. I left off the border and shadow because it looked weird. I did add the background color and `wrapInContainer` to the block element as well.

Weather-Tools-Sawtooth-Avalanche-Center-12-04-2025_11_22_AM

**Review by busbyk — APPROVED** [review]
🤘
