### PR TITLE
Blocks: Allow for unpopulated data & add missing thumbnails

### LINKED ISSUE #293: Blocks should handle missing data
The content block crashes the app when a background color is not set. This can happen when adding it as a new block and using live preview. 

Steps to reproduce: 
1. Open live preview on any Page document
2. Add a content block to the layout

Image

This will likely happen for any component using the [color field](https://github.com/NWACus/web/blob/main/src/fields/color.ts) but might be a larger issue to explore. I think the scenario where this will happen is anywhere we're accessing attributes of a field on a block that doesn't have a default value for that field. 

Even though a field is required by Payload that doesn't mean it will be present because of live preview. If it's required _and_ there's a default value that's probably safer. 

We probably also want to add error boundaries so we don't get the default next.js error boundary but I'll add that as a separate issue.

### LINKED ISSUE #301: Blocks: Add missing layout preview images
When adding a new block, some "preview" images are missing. Finish adding these.

Image

### PR DESCRIPTION
**Pull request by rchlfryn**
### Description
- Previously, some blocks would break when added while viewing the live preview. This update introduces graceful handling to prevent such issues when users add blocks with the live preview open.
- Adds missing thumbnails for blocks

### Issue
Fixes #293 & fixes #301

### CODE REVIEW

File: src/blocks/Biography/config.tsx [hunk 1]
```diff
@@ -9,11 +9,19 @@ export const BiographyBlock: Block = {
       relationTo: 'biographies',
       hasMany: false,
       required: true,
+      filterOptions: ({ data }) => {
+        return {
+          tenant: {
+            equals: data.tenant,
+          },
+        }
+      },
```
Comment (busbyk) [inline src/blocks/Biography/config.tsx]: It would be great to create a separate utility function for this tenant filter for relationship field filterOptions. Apparently, we should really be using this everywhere we have a relationship field to a collection that's tenant scoped (essentially all of them).

File: src/blocks/Biography/Biography.tsx
Comment (busbyk) [inline src/blocks/Biography/Biography.tsx:1]: Ooo nice, does this also resolve #146? 

I am getting a bunch of nested element errors though: 
CleanShot 2025-07-27 at 12 36 08

File: src/components/ColorPicker/index.tsx [hunk 2]
```diff
@@ -17,25 +17,35 @@ const ColorPicker = (props: TextFieldClientProps) => {
     'brand-800',
     'brand-900',
     'brand-950',
+    'transparent',
```
Comment (busbyk) [inline src/components/ColorPicker/index.tsx:20]: Ahh that's what this is 
CleanShot 2025-07-27 at 12 43 40@2x

That wasn't clear to me. Hmm I wonder if we could like add a tooltip or use a grid-like image like: 
CleanShot 2025-07-27 at 12 44 44@2x

?

**Review by busbyk — CHANGES_REQUESTED** [review]
The thumbnails look great! Looks like we're still missing one for the form block though: 
CleanShot 2025-07-27 at 12 31 05@2x

Just a couple things but looks great!

File: src/components/ColorPicker/index.tsx (hunk 2 above)
Comment (rchlfryn) [reply src/components/ColorPicker/index.tsx:20]: I was being lazy - updated in [969b561](https://github.com/NWACus/web/pull/360/commits/969b5619b9df6e8d3cdd2476b8c270e39352258c)

File: src/blocks/Biography/Biography.tsx
Comment (rchlfryn) [reply src/blocks/Biography/Biography.tsx:1]: Wow - I copied th dialog from Shadcn and it was so wrong. Fixed in [9a460cf](https://github.com/NWACus/web/pull/360/commits/9a460cf1f452f626c1949fc55d2a786dd510f435)
Screenshot 2025-07-27 at 13 33 16

File: src/blocks/Biography/config.tsx (hunk 1 above)
Comment (rchlfryn) [reply src/blocks/Biography/config.tsx]: Agreed - done in [bc1dd35](https://github.com/NWACus/web/pull/360/commits/bc1dd35d26ac67316396f7d64daf6dc1a9b160e1)

**Comment by rchlfryn** [comment]
@busbyk I think I am going to hold off on adding this since I am not confident we will even keep Forms block. From the way it is sounding, every form will be embedded.

**Review by busbyk — APPROVED** [review]
Looks great, thanks for making those changes!

There are a few things that will still need to be done on #146 but I'll add those to that issue.
