### PR TITLE
Bugfix: Fixing event date hydration error

### LINKED ISSUE #751: Hydration error on /events due to dates
**Describe the bug**
We get a hydration error (observed in the browser console as a minified react error) on /events because the large date in the upper left of event previews does not respect the startDate field's timezone. 

A simple fix to use the same formatDateTime utility function that uses the timezone as the rest of the preview card. 

**To Reproduce**

1. Visit https://www.avy-fx-demo.org/events

You'll notice that you see a flash of different dates due to server vs. client rendering. 

**Expected behavior**
No hydration error

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by busbyk**
## Description

Fix date hydration errors on event cards by using timezone-aware date formatting.

## Related Issues

Fixes #751

## Key Changes

- Replace raw `new Date()` methods with `formatDateTime()` in EventPreview for the large date sidebar display
- Replace `isSameDay()` from date-fns with timezone-aware comparison in StartAndEndDateDisplay
- Add test event seed data with midnight UTC start time to reproduce the issue

## Screenshots / Demo

No hydration error :)

CleanShot 2026-01-11 at 21 17 47@2x

## Rule of thumb for hydration mismatches for dates

**Triggering date hydration errors:** Hydration mismatches occur when a date falls on different calendar days in UTC vs the user's timezone:

| User Timezone | Problematic UTC Times |
|--------------|----------------------|
| US (behind UTC) | Early morning UTC (00:00-08:00) |
| Ahead of UTC | Late evening UTC (16:00-23:59) |

To test locally: `TZ=UTC pnpm dev`

### CODE REVIEW

File: src/components/StartAndEndDateDisplay.tsx [hunk 1]
```diff
@@ -1,6 +1,18 @@
...
+
+// Timezone-aware same-day comparison to avoid hydration mismatches
+// Compares the formatted date strings in the event's timezone rather than local timezone
+const isSameDayInTimezone = (
+  date1: string,
+  tz1: string | null | undefined,
+  date2: string,
+  tz2: string | null | undefined,
+): boolean => {
+  const day1 = formatDateTime(date1, tz1, 'yyyy-MM-dd')
```
Comment (stevekuznetsov) [inline src/components/StartAndEndDateDisplay.tsx]: Instead of doing stringly-typed comparisons, create a timezone-aware Date object and do the comparison itself.

File: src/components/StartAndEndDateDisplay.tsx [hunk 2]
```diff
@@ -1,6 +1,18 @@
 import type { Event } from '@/payload-types'
 import { formatDateTime } from '@/utilities/formatDateTime'
-import { isSameDay } from 'date-fns'
+
+// Timezone-aware same-day comparison to avoid hydration mismatches
+// Compares the formatted date strings in the event's timezone rather than local timezone
+const isSameDayInTimezone = (
```
Comment (rchlfryn) [inline src/components/StartAndEndDateDisplay.tsx]: This function is fine but `isSameDay` had options to account for timezones if you wanted to use that 
https://date-fns.org/v4.1.0/docs/isSameDay#

So something like this would work.
```ts
const result = isSameDay(date1, date2, {
  in: (date) => new TZDate(date, "UTC") // Normalize to a specific timezone
});
```

File: src/endpoints/seed/events.ts [hunk 3]
```diff
@@ -258,5 +278,39 @@ export const getEventsData = (
         'Your observations make a difference! Community data is essential for accurate avalanche forecasting.',
       ),
     },
+
+    // HYDRATION ERROR TEST EVENT
```
Comment (rchlfryn) [inline src/endpoints/seed/events.ts:282]: This would be nice to convert into an actual test once we have our test suite up.

**Review by rchlfryn — APPROVED** [review]

File: src/endpoints/seed/events.ts (hunk 3 above)
Comment (busbyk) [reply src/endpoints/seed/events.ts:282]: Yea an integration test via Playwright or similar, totally. A more generic check for hydration errors on various pages seems like a good idea.

File: src/components/StartAndEndDateDisplay.tsx [hunk 4]
```diff
@@ -10,7 +11,7 @@ export function StartAndEndDateDisplay({
 }: Pick<Event, 'startDate' | 'startDate_tz' | 'endDate' | 'endDate_tz'>) {
   return (
     <>
-      {endDate && isSameDay(startDate, endDate) ? (
+      {endDate && isSameDay(startDate, endDate, { in: tz(startDate_tz ?? undefined) }) ? (
```
Comment (rchlfryn) [inline src/components/StartAndEndDateDisplay.tsx]: why is `undefined` here?

**Review by rchlfryn — APPROVED** [review]
LG - just one minor comment

File: src/components/StartAndEndDateDisplay.tsx (hunk 4 above)
Comment (busbyk) [reply src/components/StartAndEndDateDisplay.tsx]: Yep, we could remove it
