### PR TITLE
Fix tenant selector for global & readd to dashboard

### LINKED ISSUE #712: Tenant not set in TenantSelector when visiting global collection
**Describe the bug**
When you visit a global collection by clicking on it in the admin panel nav, the [global view redirect](src/utilities/tenancy/getGlobalViewRedirect.ts) should navigatesto the currently set tenant or the first tenant option's document view and set the tenant in the [TenantSelector](src/components/TenantSelector). The redirect happens correctly but the tenant is not set in the TenantSelector. 

**To Reproduce**

1. Visit localhost:3000/admin
2. Click on "Home Page" in the nav
3. Wait for the redirect, observe that the TenantSelector is not set: 

**Expected behavior**
When you visit a global collection by clicking on it in the admin panel nav, the [global view redirect](src/utilities/tenancy/getGlobalViewRedirect.ts) correctly navigates to the currently set tenant or the first tenant option's document view and sets the tenant in the [TenantSelector](src/components/TenantSelector).

**Screenshots**
https://www.loom.com/share/aa4e5630346b45428f5ebfc63ca1bf79

**Environment details**

- Desktop
- Chrome

### PR DESCRIPTION
**Pull request by rchlfryn**
## Description
Fixed the tenant selector not being set on global view & re-added it to the dashboard. I choose to not fully copy everything over because it was taking longer than I expected and we should make a follow up ticket for this if we want it

## Related Issues
Fixes #712 

## Key Changes
- I copied the provider files from the latest [multi-tenant-plugin..v3.67.0](https://github.com/payloadcms/payload/tree/v3.67.0/packages/plugin-multi-tenant/src/providers/TenantSelectionProvider) files. The main things I did not copy over..
  - updating `getTenantOptions` to use `tenantsArrayFieldName`, tenantsArrayTenantFieldName`, and `userHasAccessToAllTenants` 
  - the `populate-teanant-options` endpoint and use of it
    - https://github.com/payloadcms/payload/blob/v3.67.0/packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.client.tsx#L173-L179
    - https://github.com/payloadcms/payload/blob/v3.67.0/packages/plugin-multi-tenant/src/endpoints/getTenantOptionsEndpoint.ts

## Future enhancements / Questions
Update all the other multi-tenant files

### CODE REVIEW

File: src/utilities/tenancy/generateCookie.ts [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+  name: string
+  path?: string
+  sameSite?: 'Lax' | 'None' | 'Strict'
+  secure?: boolean
+  value: string | undefined
+}
+
+export const generateCookie = <ReturnCookieAsObject = boolean>(
+  args: CookieOptions,
+): ReturnCookieAsObject extends true ? CookieObject : string => {
```
Comment (busbyk) [inline src/utilities/tenancy/generateCookie.ts]: Function overloads to get the return types to play nicely:

```
type BaseCookieOptions = {
  domain?: string
  expires?: Date
  httpOnly?: boolean
  maxAge?: number
  name: string
  path?: string
  sameSite?: 'Lax' | 'None' | 'Strict'
  secure?: boolean
  value?: string
}

type CookieOptionsAsObject = BaseCookieOptions & { returnCookieAsObject: true }
type CookieOptionsAsString = BaseCookieOptions & { returnCookieAsObject: false }
type CookieOptions = CookieOptionsAsObject | CookieOptionsAsString

type CookieObject = {
  domain?: string
  expires?: string
  httpOnly?: boolean
  maxAge?: number
  name: string
  path?: string
  sameSite?: 'Lax' | 'None' | 'Strict'
  secure?: boolean
  value: string | undefined
}

// Function overloads
export function generateCookie(args: CookieOptionsAsObject): CookieObject
export function generateCookie(args: CookieOptionsAsString): string
export function generateCookie(args: CookieOptions): CookieObject | string {
```

File: src/utilities/tenancy/generateCookie.ts [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+  if (sameSite) {
+    if (returnCookieAsObject) {
+      cookieObject.sameSite = sameSite
+    } else {
+      cookieString += `; SameSite=${sameSite}`
+    }
+  }
+
+  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions, @typescript-eslint/no-explicit-any
+  return returnCookieAsObject ? (cookieObject as any) : (cookieString as any)
```
Comment (busbyk) [inline src/utilities/tenancy/generateCookie.ts]: We could use function overloads to get these types to be inferred correctly. See above. Then we could remove the addition to `consistent-type-assertions.txt`.

**Review by busbyk — COMMENTED** [review]
Just one comment about the type assertions. Aside from that, looks great!

I know that type assertion is from Payload but we might as well try to follow our rule of not adding additional type assertions.

**Review by busbyk — APPROVED** [review]
📈
