### PR TITLE
Fix video rendering

### LINKED ISSUE #299: VideoMedia causes hydration error
It just needs to use `getMediaURL` with `getHostnameFromTenant` like the ImageMedia https://github.com/NWACus/web/blob/main/src/components/Media/ImageMedia/index.tsx#L59

But there are also commented out lines in there and we may want to add video controls to the video element. It just plays on a loop right now.

### PR DESCRIPTION
**Pull request by rchlfryn**
### Description
When adding a video through the media block, it was causing a hydration error and not loading. This PR fixes that bug.

### Issues
Fixes #299

### CODE REVIEW

File: src/components/Media/VideoMedia/index.tsx [hunk 1]
```diff
@@ -3,12 +3,14 @@
...
+import { getHostnameFromTenant } from '@/utilities/tenancy/getHostnameFromTenant'
 import type { Props as MediaProps } from '../types'
 
 export const VideoMedia = (props: MediaProps) => {
-  const { onClick, resource, videoClassName } = props
-
+  const { onClick, resource, showVideoControls, videoClassName } = props
+  const { tenant } = useTenant()
   const videoRef = useRef<HTMLVideoElement>(null)
   // const [showFallback] = useState<boolean>()
```
Comment (busbyk) [inline src/components/Media/VideoMedia/index.tsx]: Should we just remove this and the useEffect if we're not actually rendering a fallback?

File: src/components/Media/VideoMedia/index.tsx [hunk 2]
```diff
@@ -23,20 +25,23 @@ export const VideoMedia = (props: MediaProps) => {
...
+    const cacheTag = resource.updatedAt
+
+    const src = getMediaURL(url, cacheTag, getHostnameFromTenant(tenant))
 
     return (
       <video
         autoPlay
         className={cn(videoClassName)}
-        controls={false}
+        controls={showVideoControls || true}
```
Comment (busbyk) [inline src/components/Media/VideoMedia/index.tsx]: I think we should use nullish coalescing here because if `showVideoControls` is passed as `false` it would actually evaluate to `true` with the use of `||` here. 

```suggestion
        controls={showVideoControls ?? true}
```

File: src/components/Media/VideoMedia/index.tsx [hunk 3]
```diff
@@ -23,20 +25,23 @@ export const VideoMedia = (props: MediaProps) => {
...
   if (resource && typeof resource === 'object') {
-    const { filename } = resource
+    const { url } = resource
+    const cacheTag = resource.updatedAt
+
+    const src = getMediaURL(url, cacheTag, getHostnameFromTenant(tenant))
 
     return (
       <video
         autoPlay
```
Comment (busbyk) [inline src/components/Media/VideoMedia/index.tsx]: What do you think about just turning autoPlay off?

**Review by busbyk — CHANGES_REQUESTED** [review]

**Review by busbyk — APPROVED** [review]
🤘
